# Generated by Django 3.0.4 on 2020-03-23 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='subscribed_to',
        ),
        migrations.AddField(
            model_name='blog',
            name='subscribed_to',
            field=models.ManyToManyField(related_name='subscribed_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
