# Generated by Django 3.0.4 on 2020-03-24 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_blog_ManyToMany'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='read_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='read_posts', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subscribed_to',
            field=models.ManyToManyField(blank=True, related_name='subscribed_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
